apiVersion: v1
kind: Pod
metadata:
  name: ksimple-boot
  labels: 
     env: prod
     owner: bugakov
spec:
  containers: 
      - name: ksimple-boot 
        image: svbugakov/kuber:simole-boot
        ports:
          - containerPort: 8080
